firstName = input("Enter your First Name: ")
lastName = input("Enter your Last Name: ")
middleName = input("Enter your Middle Name: ")
birthday = input("Enter Date of Birth: ")
gender = input("Enter your Gender M/F: ")
Address = input("Enter your Address: ")
Course = input("Enter your Course: ")
yrLvl = input("Enter your Level: ")
print(" ")


print("============================================")
print("Full Name:" + " " + firstName + " " + middleName + " " + lastName )
print("Birthday:", birthday)
print("Gender:", gender)
print("Address:", Address)
print("Course:", Course)
print("Year level:", yrLvl)
print("============================================")